//
// Created by stefan on 1/15/24.
//


//Valid values
//CMAKE_BUS_TOPOLOGY_CAR_WITH_PI
//CMAKE_BUS_TOPOLOGY_SLED_NO_PI
//CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI

#ifndef CMAKE_BUS_TOPOLOGY_CAR_WITH_PI
#define CMAKE_BUS_TOPOLOGY_CAR_WITH_PI 0
#endif

#ifndef CMAKE_BUS_TOPOLOGY_SLED_NO_PI
#define CMAKE_BUS_TOPOLOGY_SLED_NO_PI 1
#endif

#ifndef CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI
#define CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI 2
#endif

#cmakedefine CMAKE_BUS_TOPOLOGY @CMAKE_BUS_TOPOLOGY_VALUE@
//
//#ifdef CMAKE_BUS_TOPOLOGY
//    #if (CMAKE_BUS_TOPOLOGY == CMAKE_BUS_TOPOLOGY_CAR_WITH_PI)
//    #define CMAKE_BUS_TOPOLOGY_CAR_WITH_PI
//    #elif (CMAKE_BUS_TOPOLOGY == CMAKE_BUS_TOPOLOGY_SLED_NO_PI)
//    #define CMAKE_BUS_TOPOLOGY_SLED_NO_PI
//    #elif (CMAKE_BUS_TOPOLOGY == CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI)
//    #define CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI
//    #endif
//#endif
//
//#ifdef CMAKE_BUS_TOPOLOGY
//    #if
//    #define CMAKE_BUS_TOPOLOGY_SLED_NO_PI
//    #endif
//#endif
//
//#ifdef CMAKE_BUS_TOPOLOGY
//    #if (CMAKE_BUS_TOPOLOGY == CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI)
//    #define CMAKE_BUS_TOPOLOGY_SLED_LAPTOP_HMI
//    #endif
//#endif