/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "ConfigProto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ca_stefanm_e39_proto_ConfigProto, ca_stefanm_e39_proto_ConfigProto, AUTO)








