//
// Created by stefan on 2/22/24.
//

//Valid Values
// CMAKE_VIDEO_SUPPORT_NO_VIDEO
// CMAKE_VIDEO_SUPPORT_HAS_VIDEO

#ifndef CMAKE_VIDEO_SUPPORT_NO_VIDEO
#define CMAKE_VIDEO_SUPPORT_NO_VIDEO 0
#endif

#ifndef CMAKE_VIDEO_SUPPORT_HAS_VIDEO
#define CMAKE_VIDEO_SUPPORT_HAS_VIDEO 1
#endif

#cmakedefine CMAKE_HAS_VIDEO_SUPPORT @CMAKE_HAS_VIDEO_VALUE@