/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_PROTO_CONFIGPROTO_PB_H_INCLUDED
#define PB_PROTO_CONFIGPROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PROTO_TestMessage {
    pb_callback_t str;
} PROTO_TestMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PROTO_TestMessage_init_default           {{{NULL}, NULL}}
#define PROTO_TestMessage_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define PROTO_TestMessage_str_tag                1

/* Struct field encoding specification for nanopb */
#define PROTO_TestMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   str,               1)
#define PROTO_TestMessage_CALLBACK pb_default_field_callback
#define PROTO_TestMessage_DEFAULT NULL

extern const pb_msgdesc_t PROTO_TestMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PROTO_TestMessage_fields &PROTO_TestMessage_msg

/* Maximum encoded size of messages (where known) */
/* PROTO_TestMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
